language: objective-c
osx_image: xcode9.2

before_script:
  - bundle exec danger

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty
  - carthage bootstrap --verbose --no-use-binaries --platform mac --cache-builds

script:
  - set -o pipefail
  - xcodebuild -project HSTracker.xcodeproj -scheme HSTracker -sdk macosx clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

