language: objective-c
osx_image: xcode9.4

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew outdated carthage || brew upgrade carthage
  - ./bootstrap.sh

script:
  - bundle exec fastlane ci

