language: objective-c
osx_image: xcode8.3
rvm: 2.0.0

before_script:
  - bundle exec danger

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty
  - carthage update --no-use-binaries --platform mac

script:
  - set -o pipefail 
  - xcodebuild -project HSTracker.xcodeproj -scheme HSTracker -sdk macosx clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

